# Site settings
name: huoshenglong.github
email: long606186@163.com
author: huoshenglong
url: https://huoshenglong.github.io
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/huoshenglong/huoshenglong.github.io
baseurl: ""
description: Actually, less is more!
meta_description: Just do it!
motto: It's our wits that make us men.
banner: To learn more anytime! 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: huoshenglong

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

